<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Hypertrophy.Domain/Hypertrophy.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions/Behaviors/" />
    <Folder Include="Abstractions/Clock/" />
    <Folder Include="Abstractions/Exceptions/" />
    <Folder Include="Abstractions/Mediator/" />
    <Folder Include="Abstractions/Pagination/" />
    <Folder Include="Exercise/" />
    <Folder Include="Exercise/CreateExercise/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="9.0.8" />
  </ItemGroup>

</Project>
